In [81]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [82]:
data = pd.read_csv("car.data")

In [83]:
data.head()

buying maintenance doors persons lug_boot safety  class
0  vhigh       vhigh     2       2    small    low  unacc
1  vhigh       vhigh     2       2    small    med  unacc
2  vhigh       vhigh     2       2    small   high  unacc
3  vhigh       vhigh     2       2      med    low  unacc
4  vhigh       vhigh     2       2      med    med  unacc

In [18]:
#creating labels and features
#X == labels,y == features(class or the last part of the dataset)

In [84]:
x = data[['buying','maintenance','safety']].values

In [85]:
y = data[['class']]

In [86]:
print(x,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [25]:
#converting the x data 
#Converting the words into numbers because words can't be put in the ML algorithm

In [87]:
Le = LabelEncoder()

In [88]:
for i in range(len(x[0])):
    x[:,i]= Le.fit_transform(x[:,i])

In [89]:
x

array([[3, 3, 1],
       [3, 3, 2],
       [3, 3, 0],
       ...,
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 0]], dtype=object)

In [34]:
#converting the y data

In [90]:
label_mapping = {'unacc':0,'acc':1,'good':2,'vgood':3}#using a dictionary
y['class'] = y['class'].map(label_mapping)
y = np.array(y)#converting y data to a numpy array
y

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([[0],
       [0],
       [0],
       ...,
       [0],
       [2],
       [3]], dtype=int64)

In [36]:
#create the model

In [91]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

In [92]:
#training the model
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
 #test size is the percentage of our data for training purposes (0.2= 20%)

In [93]:
knn.fit(x_train,y_train)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

In [94]:
predictions = knn.predict(x_test)

In [100]:
accuracy = metrics.accuracy_score(y_test,predictions)

In [96]:
predictions

array([0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 1, 0, 0, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 3,
       2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2,
       0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 3, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,

In [101]:
accuracy

0.7341040462427746

In [102]:
print("actual value: ", y[20])

actual value:  [0]


In [54]:
#printing the predicted value

In [103]:
print("Predicted Value:", knn.predict(x)[20])

Predicted Value: 0


In [106]:
print("actual value: ", y[1727])

actual value:  [3]


In [107]:
print("Predicted Value:", knn.predict(x)[1727])

Predicted Value: 3
